substitutions:
  status_led_pin: GPIO35
  status_led_brightness: "50%"'
  number_leds: 4
  rgb_ordering: GRB
  led_chipset: WS2812
  # ID for the microcontroller connected binary_sensor
  micro_connected_id: microcontroller_connected
  # ID for the alarm count sensor
  alarm_id: alarm_count

# This was tested on an AtomS3 and S3-lite
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    pin: 
      number: ${status_led_pin}
      allow_other_uses: true
    num_leds: ${number_leds}
    rgb_order: ${rgb_ordering}
    chipset: ${led_chipset}
    internal: true
    effects:
      - pulse:
          name: "Breathing"
          transition_length: 1s
          update_interval: 1s
          min_brightness: 5%
          max_brightness: ${status_led_brightness}
      - strobe:
          name: "Error Flash"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 100ms
            - state: false
              duration: 100ms

interval:
  - interval: 1s
    then:
      - if:
          condition:
            not:
              wifi.connected:
          then:
            # 1. No WiFi -> Fast Red Flash
            - light.turn_on:
                id: status_led
                effect: "Error Flash"
          else:
            # - if:
            #     condition:
            #       not:
            #         binary_sensor.is_on: ${micro_connected_id}
            #     then:
            #       # 2. Microcontroller Disconnected -> Solid Purple
            #       - light.turn_on:
            #           id: status_led
            #           brightness: ${status_led_brightness}
            #           red: 80%
            #           green: 0%
            #           blue: 100%
            #           effect: "none"
            #     else:
                  - if:
                      condition:
                        not:
                          api.connected:
                      then:
                        # 3. WiFi OK, MCU OK, No API -> Solid Blue
                        - light.turn_on:
                            id: status_led
                            brightness: ${status_led_brightness}
                            red: 0%
                            green: 0%
                            blue: 100%
                            effect: "none"
                      else:
                        # 4. Connected + Alarm Count > 0 -> Solid Amber
                        - if:
                            condition:
                              lambda: 'return id(${alarm_id}).state > 0;'
                            then:
                              - light.turn_on:
                                  id: status_led
                                  brightness: ${status_led_brightness}
                                  red: 100%
                                  green: 50%
                                  blue: 0%
                                  effect: "none"
                            else:
                              # 5. All Normal -> Breathing Green
                              - light.turn_on:
                                  id: status_led
                                  brightness: ${status_led_brightness}
                                  red: 0%
                                  green: 100%
                                  blue: 0%
                                  effect: "Breathing"
